### PR TITLE
Only convert units for species that require it

### LINKED ISSUE #1701: Implement updates to allow unit conversions for all species or per species
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### New GEOS-Chem feature or discussion
I have been comparing the performance of the carbon simulation (with KPP) using a single advected CH4 species vs. the traditional CH4 specialty simulation.  One of the areas where the carbon (single CH4) simulation underperforms is in unit conversions.  

In the various routines in `GeosUtil/unitconv_mod.F90`, we convert all units (both advected and KPP/non-advected) upon entry to each operation and then do the inverse unit conversion.  For some operations (e.g. transport, convection, wetdep), we may only need to convert advected species, since the non-advected species are not touched.  This can have a big impact on simulations like single tracer carbon, as there are several KPP-only species that need to be present in the mechanism but only 1 advected species.

I propose adding an optional argument to the unit conversion routines to indicate that only advected species should be considered in unit conversions.

### LINKED ISSUE #1820: Discussion: Species units metadata and species unit conversion
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/reference/CONTRIBUTING.html)

### New GEOS-Chem discussion

Updates for the TransportTracers simulation (see PR #1816) have introduced a units string into the species database (e.g. for age of air)

```console
aoa:
  FullName: Age of air uniform source tracer
  Is_Advected: true
  Is_Gas: true
  Is_Tracer: true
  Snk_Horiz: all
  Snk_Mode: constant
  Snk_Value: 0
  Snk_Vert: surface
  Src_Add: true
  Src_Horiz: all
  Src_Mode: constant
  Src_Units: timestep
  Src_Value: 1
  Src_Vert: all
  Units: days
```
However, we might also be well-served by adding a units (and previous units) fields to the `State_Chm%Species` object:
```F90
State_Chm%Species(N)%Conc(I,J,L)
State_Chm%Species(N)%Units
State_Chm%Species(N)%PreviousUnits
```
We may also need to be cognizant of any special handling for operating in the MPI environment (e.g. the species database in CESM-GC is only read on the first core, and then a pointer is kept for the other cores).

Thoughts: @msulprizio @lizziel @jimmielin

### LINKED ISSUE #2250: Out-of-the-Box GEOS-Chem Classic TOMAS simulations fail due to species not found in restart file
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Out-of-the-box GEOS-Chem Classic TOMAS15 runs fail with this error:

```console
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
 
HEMCO ERROR: Cannot find field SPC_BUTDI. Please check variable name in the config. file
 
HEMCO ERROR: Error encountered in routine HCOIO_Read!
 
HEMCO ERROR: Error in HCOIO_DATAREAD called from HEMCO ReadList_Fill: SPC_BUTDI
 --> LOCATION: ReadList_Fill (HCO_ReadList_Mod.F90)
 
HEMCO ERROR: Error in called ReadList_Fill (7) from HEMCO ReadList_Read
 --> LOCATION: ReadList_Read (HCO_ReadList_Mod.F90)
 Error in ReadList_Read called from hco_run
===============================================================================
GEOS-Chem ERROR: Error encountered in "HCO_Run"!
 -> at HCOI_GC_Run (in module GeosCore/hco_interface_gc_mod.F90)

THIS ERROR ORIGINATED IN HEMCO!  Please check the HEMCO log file for 
additional error messages!
===============================================================================
```
This is because the time-cycle setting for the restart file is set to `EFYO` instead of `EY`, and there are some species (e.g. the furans) not in the TOMAS restart file.  We can fix this by adding TOMAS15 to the list of simulations in where we change `EFYO` -> `EY` in `createRunDir.sh`.  I will add this to the PR #2072.

### PR DESCRIPTION
**Pull request by yantosca**
### Name and Institution (Required)

Name:  Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/CONTRIBUTING.html)

### Describe the update
This PR updates the unit conversion routines as follows:
- Introduces `State_Chm%Species(N)%Units` and `State_Chm%Species(N)%Previous_Units` fields
- Updates in `GeosUtil/unitconv_mod.F90`:
  - In `Convert_Spc_Units`:
    - Now accepts a `mapping` argument, specifying the `modelId` species indices
    - Argument `outUnit` is renamed to `new_units`
    - Argument `origUnit` is renamed to `previous_units`
  - Added function `Check_Units`
  - Added function `Check_Previous_Units`

Calls to `Convert_Spc_Units` throughout the code have been updated correspondingly.

### Expected changes
We will see small differences at the level of numerical noise.

### Related Github Issue(s)
- Closes #1820
- Closes #1701
- Closes #2250

### CODE REVIEW

**Comment by yantosca** [comment]
Still shaking down some bugs in the implementation.

**Comment by yantosca** [comment]
The unit conversions result in a noticeable speedup in GEOS-Chem fullchem simullations.
```console
Both runs on huce_cascade, --exclusive, 48 cores

7day fullchem benchmark run, ref (dev/no-diff-to-benchmark)

G E O S - C H E M   T I M E R S
 
  Timer name                       DD-hh:mm:ss.SSS     Total Seconds
-------------------------------------------------------------------------------
  GEOS-Chem                     :  00-00:52:27.125          3147.125
  HEMCO                         :  00-00:09:27.250           567.250
  All chemistry                 :  00-00:18:57.500          1137.500
  => Gas-phase chem             :  00-00:11:14.875           674.875
  => Photolysis                 :  00-00:01:17.250            77.250
  => Aerosol chem               :  00-00:06:06.875           366.875
  => Linearized chem            :  00-00:00:05.000             5.000
  Transport                     :  00-00:03:52.125           232.125
  Convection                    :  00-00:04:02.875           242.875
  Boundary layer mixing         :  00-00:07:14.250           434.250
  Dry deposition                :  00-00:00:10.625            10.625
  Wet deposition                :  00-00:01:32.250            92.250
  Diagnostics                   :  00-00:06:09.250           369.250
  Unit conversions              :  00-00:02:00.500           120.500

7day fullchem benchmark run, ref (feature/units-array-ops)

G E O S - C H E M   T I M E R S
 
  Timer name                       DD-hh:mm:ss.SSS     Total Seconds
-------------------------------------------------------------------------------
  GEOS-Chem                     :  00-00:48:45.750          2925.750
  HEMCO                         :  00-00:07:58.250           478.250
  All chemistry                 :  00-00:17:58.250          1078.250
  => Gas-phase chem             :  00-00:11:10.375           670.375
  => Photolysis                 :  00-00:01:18.875            78.875
  => Aerosol chem               :  00-00:05:10.375           310.375
  => Linearized chem            :  00-00:00:04.125             4.125
  Transport                     :  00-00:03:37.500           217.500
  Convection                    :  00-00:03:59.625           239.625
  Boundary layer mixing         :  00-00:06:43.750           403.750
  Dry deposition                :  00-00:00:08.250             8.250
  Wet deposition                :  00-00:01:24.250            84.250
  Diagnostics                   :  00-00:06:08.000           368.000
  Unit conversions              :  00-00:01:26.250            86.250
```

**Comment by yantosca** [comment]
From the 7-day fullchem benchmark runs shown above, most species have numerical noise differences w/r/t the prior code.  This may be because numerical computations are done in a slightly different order, which may incur roundoff.
o3

**Comment by yantosca** [comment]
As part of this PR, I am making sure that unit conversion is timed separately (i.e. halting other timers before calls to Convert_Spc_Units and starting them again afterwards).

**Comment by yantosca** [comment]
In 8d052961, we have reorganized calls to timers so that unit conversion is timed separately from other categories.  This now results in the following timing output:

All simualtions were run on the Cannon cluster on 48 cores (Intel Cascade Lake CPUs).

## 1-month carbon simulations

### Ref version: geoschem/geos-chem commit 69ae58a1
```console
G E O S - C H E M   T I M E R S
 
  Timer name                       DD-hh:mm:ss.SSS     Total Seconds
---------------------------------------------------------------------------
  GEOS-Chem                     :  00-00:16:56.312          1016.312
  HEMCO                         :  00-00:10:03.796           603.797
  All chemistry                 :  00-00:01:45.750           105.750
  => Gas-phase chem             :  00-00:01:43.250           103.250
  => Photolysis                 :  >>>>> THE TIMER DID NOT RUN <<<<<
  => Aerosol chem               :  >>>>> THE TIMER DID NOT RUN <<<<<
  => Linearized chem            :  >>>>> THE TIMER DID NOT RUN <<<<<
  Transport                     :  00-00:02:46.484           166.484
  Convection                    :  00-00:00:03.156             3.156
  Boundary layer mixing         :  00-00:00:43.593            43.594
  Dry deposition                :  >>>>> THE TIMER DID NOT RUN <<<<<
  Wet deposition                :  >>>>> THE TIMER DID NOT RUN <<<<<
  Diagnostics                   :  00-00:01:20.171            80.172
  Unit conversions              :  00-00:00:09.937             9.938
```
### Dev version: geoschem/geos-chem commit 8d052961
```console
G E O S - C H E M   T I M E R S
 
  Timer name                       DD-hh:mm:ss.SSS     Total Seconds
---------------------------------------------------------------------------
  GEOS-Chem                     :  00-00:16:11.093           971.094
  HEMCO                         :  00-00:09:43.796           583.797
  All chemistry                 :  00-00:01:19.515            79.516
  => Gas-phase chem             :  00-00:01:19.500            79.500
  => Photolysis                 :  >>>>> THE TIMER DID NOT RUN <<<<<
  => Aerosol chem               :  >>>>> THE TIMER DID NOT RUN <<<<<
  => Linearized chem            :  >>>>> THE TIMER DID NOT RUN <<<<<
  Transport                     :  00-00:02:45.984           165.984
  Convection                    :  00-00:00:02.875             2.875
  Boundary layer mixing         :  00-00:00:35.343            35.344
  Dry deposition                :  >>>>> THE TIMER DID NOT RUN <<<<<
  Wet deposition                :  >>>>> THE TIMER DID NOT RUN <<<<<
  Diagnostics                   :  00-00:01:21.515            81.516
  Unit conversions              :  00-00:00:08.312             8.312
```

## 7-day fullchem benchmark simulations:
### Ref version: geoschem/geos-chem commit 69ae58a1
```console
G E O S - C H E M   T I M E R S
 
  Timer name                       DD-hh:mm:ss.SSS     Total Seconds
---------------------------------------------------------------------------
  GEOS-Chem                     :  00-00:55:33.500          3333.500
  HEMCO                         :  00-00:09:27.500           567.500
  All chemistry                 :  00-00:23:48.531          1428.531
  => Gas-phase chem             :  00-00:12:48.968           768.969
  => Photolysis                 :  00-00:01:32.218            92.219
  => Aerosol chem               :  00-00:09:02.234           542.234
  => Linearized chem            :  00-00:00:08.781             8.781
  Transport                     :  00-00:03:04.812           184.812
  Convection                    :  00-00:03:58.906           238.906
  Boundary layer mixing         :  00-00:05:53.156           353.156
  Dry deposition                :  00-00:00:12.468            12.469
  Wet deposition                :  00-00:01:32.015            92.016
  Diagnostics                   :  00-00:06:16.000           376.000
  Unit conversions              :  00-00:01:56.640           116.641
```
### Dev version: geoschem/geos-chem commit 8d052961
```console
G E O S - C H E M   T I M E R S
 
  Timer name                       DD-hh:mm:ss.SSS     Total Seconds
---------------------------------------------------------------------------
  GEOS-Chem                     :  00-00:50:26.390          3026.391
  HEMCO                         :  00-00:08:35.781           515.781
  All chemistry                 :  00-00:20:16.921          1216.922
  => Gas-phase chem             :  00-00:11:03.578           663.578
  => Photolysis                 :  00-00:01:18.250            78.250
  => Aerosol chem               :  00-00:07:21.562           441.562
  => Linearized chem            :  00-00:00:03.343             3.344
  Transport                     :  00-00:03:00.921           180.922
  Convection                    :  00-00:03:58.671           238.672
  Boundary layer mixing         :  00-00:04:44.875           284.875
  Dry deposition                :  00-00:00:07.734             7.734
  Wet deposition                :  00-00:01:14.750            74.750
  Diagnostics                   :  00-00:06:30.062           390.062
  Unit conversions              :  00-00:01:13.703            73.703
```

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed (except for TOMAS)
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #5496180 GEOS-Chem submod update: Merge PR #2084 (Fix exe name in int tests)
GEOS-Chem #7e6fcce46 Add "USE Timers_Mod" to GeosCore/rrtmg_rad_transfer_mod.F90
HEMCO     #a5d5169 HEMCO 3.7.2 release

Using 24 OpenMP threads
Number of execution tests: 27

Submitted as SLURM job: 14261425
==============================================================================

Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 25
Execution tests failed: 2
Execution tests not yet completed: 0
```

**Comment by yantosca** [comment]
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #5692f34 GEOS-Chem submod update: Merge PR #2084 (Fix exe name in int tests)
GEOS-Chem #8f1c36897 Bug fix: Remove reference origUnit in GCHP_Chunk_Run routien
HEMCO     #a5d5169 HEMCO 3.7.2 release

Number of execution tests: 5

Submitted as SLURM job: 14351891
==============================================================================
 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by lizziel** [comment]
I will review this PR today. @yantosca, could you post the full set of comparison plots on the ftp site for review?

**Comment by lizziel** [comment]
I looks like the base of this update is the dev/no-diff branch. Could you make the base dev/14.3 before I review? The update will cause diffs so it shouldn't go into dev/no-diff.

File: GeosCore/tomas_mod.F90 [hunk 1]
```diff
@@ -249,12 +249,12 @@ SUBROUTINE DO_TOMAS( Input_Opt,  State_Chm, State_Diag, State_Grid, &
     ! Assume success
     RC    = GC_SUCCESS
 
-    ! Check that species units are in [kg] (ewl, 8/13/15)
-    IF ( State_Chm%Spc_Units /= KG_SPECIES ) THEN
-       MSG = 'Incorrect species units: ' // TRIM(UNIT_STR(State_Chm%Spc_Units))
-       LOC = 'Routine DO_TOMAS in tomas_mod.F90'
-       CALL GC_Error( MSG, RC, LOC )
-    ENDIF
+    !! Check that species units are in [kg] (ewl, 8/13/15)
```
Comment (lizziel) [inline GeosCore/tomas_mod.F90:252]: Should this check be commented out? Could we call check units?

File: GeosCore/tomas_mod.F90 [hunk 2]
```diff
@@ -427,11 +427,11 @@ SUBROUTINE AEROPHYS( Input_Opt, State_Chm, State_Grid, State_Met, &
     ! are now generally [kg/kg] in GEOS-Chem, they are converted to
     ! kg for TOMAS elsewhere in tomas_mod prior to calling this subroutine
     ! (ewl, 8/13/15)
-    IF ( State_Chm%Spc_Units /= KG_SPECIES ) THEN
-       MSG = 'Incorrect species units: ' // TRIM(UNIT_STR(State_Chm%Spc_Units))
-       LOC = 'Routine AEROPHYS in tomas_mod.F90'
-       CALL GC_Error( MSG, RC, LOC )
-    ENDIF
+    !IF ( State_Chm%Spc_Units /= KG_SPECIES ) THEN
```
Comment (lizziel) [inline GeosCore/tomas_mod.F90:430]: Same comment as above.

File: GeosCore/tomas_mod.F90 [hunk 3]
```diff
@@ -3555,6 +3555,7 @@ SUBROUTINE AQOXID( MOXID, KMIN, I, J, L, Input_Opt, &
     ! Assume success
     RC                =  GC_SUCCESS
 
+    ! TODO: Update since Spc_Units are no longer included
```
Comment (lizziel) [inline GeosCore/tomas_mod.F90:3558]: Is there work that still needs to be done here?

File: GeosCore/wetscav_mod.F90 [hunk 4]
```diff
@@ -1696,6 +1696,7 @@ SUBROUTINE WASHOUT( I,          J,         L,                    &
     UNITCHANGE_KGKG = .FALSE.
     UNITCHANGE_KGM2 = .FALSE.
 
+    ! TODO: Fix this since Spc_Units are no longer supported
```
Comment (lizziel) [inline GeosCore/wetscav_mod.F90:1699]: Looks like this still needs to be done.

File: Interfaces/GCClassic/main.F90 [hunk 5]
```diff
@@ -1891,24 +1891,48 @@ PROGRAM GEOS_Chem
           ! CH4 columns from the GOSAT instrument
           IF ( Input_Opt%GOSAT_CH4_OBS ) THEN
              IF ( ITS_A_NEW_HOUR() ) THEN
+                IF ( Input_Opt%useTimers ) THEN
```
Comment (lizziel) [inline Interfaces/GCClassic/main.F90:1894]: There are a bunch of if statements here. I wonder if this would be more efficient with a new logical that checks if any of the CH4 columns will be computed, and also embed within its a new hour:
```
IF ( Input_Opt%satellite_CH4_columns ) THEN
   IF ( ITS_A_NEW_HOUR ) THEN
         (Start timer here)
        IF ( Input_Opt%GOSAT_CH4_OBS) THEN
             ...
        ENDIF
        IF ( Input_Opt%AIRS_CH4_OBS) THEN
             ...
        ENDIF
        IF ( Input_Opt%TCCON_CH4_OBS) THEN
             ...
        ENDIF
        (End timer here)
    ENDIF
ENDIF
```

File: Interfaces/GEOS/geos_interface.F90 [hunk 6]
```diff
@@ -1276,7 +1276,7 @@ SUBROUTINE GEOS_Diagnostics( GC, IMPORT,  EXPORT, Clock, Phase, &
     REAL, POINTER                :: LFR(:,:)      => NULL()
     REAL, POINTER                :: CNV_FRC(:,:)  => NULL()
 
-    CHARACTER(LEN=ESMF_MAXSTR)   :: OrigUnit
+    INTEGER                      :: previous_units
```
Comment (lizziel) [inline Interfaces/GEOS/geos_interface.F90:1279]: Changes in this file will cause conflicts when I bring in the updates for GEOS but that's fine. I fixed the unit conversions when running GEOS on discover but haven't brought the changes back into the standard model yet.

File: GeosUtil/unitconv_mod.F90 [hunk 7]
```diff
@@ -148,39 +151,41 @@ MODULE UnitConv_Mod
...
+    INTEGER,          OPTIONAL      :: previous_units ! Previous units
 !
 ! !REMARKS:
 !  The purpose of optional output argument origUnit is to enable conversion
 !  back to the original units in a second call to Convert_Spc_Units.
 !  For example:
 !
-!      CALL Convert_Spc_Units( Input_Opt, State_Chm, State_Grid, State_Met, &
-!                              'kg/kg dry', RC, origUnit=origUnit )
+!      CALL Convert_Spc_Units( Input_Opt, State_Chm, State_Grid,       &
```
Comment (lizziel) [inline GeosUtil/unitconv_mod.F90:184]: This example doesn't look right. I think the first one should pass new_units and output previous_units, and the second one should set new_units to previous_units.

**Review by lizziel — CHANGES_REQUESTED** [review]
This is part 1 of my review. I got through everything except unitconv_mod.F90 which I will tackle a different day.

File: GeosUtil/unitconv_mod.F90 [hunk 8]
```diff
@@ -412,9 +459,32 @@ SUBROUTINE Convert_Spc_Units( Input_Opt, State_Chm, State_Grid, State_Met, &
...
+    !========================================================================
+    ! Additional checks
+    !========================================================================
+
+    ! Test if all species have mixing ratio units (needed for AIRQNT)
+    State_Chm%allSpeciesInDryMixingRatio = (                                   &
+         ALL( State_Chm%Species(:)%Units == KG_SPECIES_PER_KG_DRY_AIR         )&
+         .or.                                                                  &
+         ALL( State_Chm%Species(:)%Units == MOLES_SPECIES_PER_MOLES_DRY_AIR   )&
+    )
```
Comment (lizziel) [inline GeosUtil/unitconv_mod.F90:471]: Would it be faster to have this in a separate subroutine and only call it in AIRQNT when the check is needed? Thinking more about this, it could be a function that returns true or false.

File: GeosUtil/unitconv_mod.F90 [hunk 9]
```diff
@@ -2467,31 +2536,173 @@ SUBROUTINE ConvertBox_Kg_to_Kgm2( I, J, L, State_Chm, State_Grid, isAdjoint, RC
...
+  SUBROUTINE Check_Previous_Units( State_Chm, mapping, units, RC )
+!
+! !INPUT PARAMETERS:
+!
+    INTEGER,        INTENT(IN)    :: mapping(:)  ! Mapping to species Id
+    INTEGER,        INTENT(IN)    :: units       ! Input unit flag
+!
+! !INPUT/OUTPUT PARAMETERS:
+!
+    TYPE(ChmState), INTENT(INOUT) :: State_Chm   ! Chemistry State object
```
Comment (lizziel) [inline GeosUtil/unitconv_mod.F90:2667]: Would there be any benefit to making this a function that returns true/false?

File: GeosUtil/unitconv_mod.F90 [hunk 10]
```diff
@@ -2467,31 +2536,173 @@ SUBROUTINE ConvertBox_Kg_to_Kgm2( I, J, L, State_Chm, State_Grid, isAdjoint, RC
...
+!BOP
+!
+! !IROUTINE: Check_Units
+!
+! !DESCRIPTION: Ensures that all species have the same Units value before
+!  unit conversion is done.
+!\\
+! !INTERFACE:
+!
+  SUBROUTINE Check_Units( State_Chm, mapping, units, RC )
```
Comment (lizziel) [inline GeosUtil/unitconv_mod.F90:2596]: Would there be any benefit to making this a function returning true/false?

**Review by lizziel — COMMENTED** [review]
Thanks @yantosca for this update. I finished reviewing unitconv_mod (review part 2 of 2). I left a bunch of comments. I'll do another full review once you get to them all. No rush.

File: GeosUtil/unitconv_mod.F90 (hunk 8 above)
Comment (yantosca) [reply GeosUtil/unitconv_mod.F90:471]: Good point @lizziel.  I'll see how best to implement it.

File: GeosUtil/unitconv_mod.F90 [hunk 11]
```diff
@@ -148,39 +151,41 @@ MODULE UnitConv_Mod
...
 ! !INPUT PARAMETERS:
 !
-    TYPE(OptInput),   INTENT(IN)    :: Input_Opt   ! Input Options object
-    TYPE(GrdState),   INTENT(IN)    :: State_Grid  ! Grid state object
-    TYPE(MetState),   INTENT(IN)    :: State_Met   ! Meteorology state object
-    INTEGER,          INTENT(IN)    :: outUnit     ! Desired output unit
+    TYPE(OptInput),   INTENT(IN)    :: Input_Opt      ! Input Options object
+    TYPE(GrdState),   INTENT(IN)    :: State_Grid     ! Grid state object
+    TYPE(MetState),   INTENT(IN)    :: State_Met      ! Meteorology state object
+    INTEGER,          INTENT(IN)    :: mapping(:)     ! Species map to modelId
```
[the remark this answers is not in the document]
Comment (yantosca) [reply GeosUtil/unitconv_mod.F90:167]: @lizziel: we could do this:
```F90
  SUBROUTINE Convert_Spc_Units( Input_Opt, State_Chm,     State_Grid,        &
                                State_Met, mapping,       new_units,         &
                                RC,        previous_units                   )
... etc not shown ...

    INTEGER,          POINTER       :: mapping(:)     ! Species map to modelId

... etc not shown ...

    ! Convert units for all species unless mapping is passed
    ! NOTE: Avoid an ELSE statement here, which can be a bottleneck.
    theMapping => State_Chem%Map_All
    IF ( PRESENT( mapping ) ) theMapping => mapping

... etc. not shown ...

   theMapping => NULL()
```

[the remark this answers is not in the document]
Comment (yantosca) [reply GeosUtil/unitconv_mod.F90]: @lizziel: This is now updated in commit 4d3b0e9b7.  The `mapping` argument is now an `INTEGER, OPTIONAL, POINTER` argument.  We also use a local pointer within `Convert_Spc_Units` that points to `mapping` (if passed), or to `State_Chm%Map_All` (i.e. all species) if not passed.

File: GeosUtil/unitconv_mod.F90 (hunk 8 above)
Comment (yantosca) [reply GeosUtil/unitconv_mod.F90]: @lizziel: `State_Chm%allSpeciesInDryMixingRatio` has now been converted to a PRIVATE function in `GeosCore/calc_met_mod.F90` in commit 79d211841.

File: GeosUtil/unitconv_mod.F90 (hunk 10 above)
Comment (yantosca) [reply GeosUtil/unitconv_mod.F90]: @lizziel: This has been done in commit a80f173.  Having `Check_Units` be a function simplifies the code quite a bit.

File: GeosUtil/unitconv_mod.F90 (hunk 9 above)
Comment (yantosca) [reply GeosUtil/unitconv_mod.F90]: We have also removed the `Check_Previous_Units` routine as this is not really used.  It will also save some CPU cycles.

File: GeosUtil/unitconv_mod.F90 [hunk 12]
```diff
@@ -205,100 +210,125 @@ SUBROUTINE Convert_Spc_Units( Input_Opt, State_Chm, State_Grid, State_Met, &
...
+       errMsg = 'The "mapping" argument has zero elements!'
+       CALL GC_Error( errMsg, RC, thisLoc )
+       RETURN
+    ENDIF
+
     ! Initialize
-    RC        =  GC_SUCCESS
-    inUnit    = State_Chm%Spc_Units
+    RC        = GC_SUCCESS
+    in_units  = State_Chm%Species(mapping(1))%Units
```
[the remark this answers is not in the document]
Comment (yantosca) [reply GeosUtil/unitconv_mod.F90:229]: There is a call to `Check_Units` further down:
```F90
    ! Initialize
    RC        = GC_SUCCESS
    in_units  = State_Chm%Species(mapping(1))%Units
    isAdjoint = .FALSE.
    thisLoc   = ' -> at Convert_Spc_Units (in GeosUtil/unitconv_mod.F90)'
    errNoOut  = 'Conversion to '            // TRIM( UNIT_STR(new_units)) // &
                ' not defined!'
    errNoIn   = 'Conversion from '          // TRIM( UNIT_STR(in_units )) // &
                ' not defined!'
    errMsg    = 'Error in conversion from ' // TRIM( UNIT_STR(in_units )) // &
                ' to '                      // TRIM( UNIT_STR(new_units)) // &
                '!'
    errUnits  = ''

    ! TODO: Re-enable debug print
    ! Debugging print
    IF ( Input_Opt%Verbose ) THEN
       WRITE(6,'(a)') '     ### Species Unit Conversion: ' //                &
                      TRIM( UNIT_STR(in_units ) )          // ' -> ' //      &
                      TRIM( UNIT_STR(new_units) )          // ' ###'
    ENDIF

    ! Exit if in and out units are the same
    IF ( new_units == in_units ) THEN
       IF ( PRESENT( previous_units ) ) previous_units = new_units
       IF ( Input_Opt%useTimers ) THEN
          CALL Timer_End( "Unit conversions", RC )
       ENDIF
       RETURN
    ENDIF

    ! Make sure all species have consistent starting units
    IF ( .not. Check_Units( State_Chm, in_units, theMapping ) ) THEN
       errMsg = 'All species do not have consistent starting units!'
       theMapping => NULL()
       CALL GC_Error( errMsg, RC, thisLoc )
       RETURN
    ENDIF
```

File: GeosUtil/unitconv_mod.F90 [hunk 13]
```diff
@@ -602,19 +676,12 @@ SUBROUTINE ConvertSpc_KgKgDry_to_VVDry( State_Chm, State_Grid, isAdjoint, RC )
...
-    ! Verify correct initial units. If current units are unexpected,
-    ! write error message and location to log, then pass failed RC
-    ! to calling routine.
-    IF ( State_Chm%Spc_Units /= KG_SPECIES_PER_KG_DRY_AIR ) THEN
-       errMsg  = 'Incorrect initial units: '                              // &
-                  TRIM( UNIT_STR( State_Chm%Spc_Units ) )
-       thisLoc = 'Routine ConvertSpc_KgKgDry_to_VVDry in unitconv_mod.F90'
-       CALL GC_Error( errMsg, RC, thisLoc )
-       RETURN
-    ENDIF
```
[the remark this answers is not in the document]
Comment (yantosca) [reply GeosUtil/unitconv_mod.F90:617]: @lizziel: in `Convert_Spc_Units` at line 258 there is a call to `Check_Units:`
```F90
    ! Make sure all species have consistent starting units
    IF ( .not. Check_Units( State_Chm, in_units, theMapping ) ) THEN
       errMsg = 'All species do not have consistent starting units!'
       theMapping => NULL()
       CALL GC_Error( errMsg, RC, thisLoc )
       RETURN
    ENDIF
```

File: GeosUtil/unitconv_mod.F90 [hunk 14]
```diff
@@ -193,10 +198,10 @@ SUBROUTINE Convert_Spc_Units( Input_Opt, State_Chm, State_Grid, State_Met, &
 !
     ! Scalars
     LOGICAL            :: isAdjoint
-    INTEGER            :: inUnit
+    INTEGER            :: in_units
```
[the remark this answers is not in the document]
Comment (yantosca) [reply GeosUtil/unitconv_mod.F90]: @lizziel: The `in_units` variable has been renamed to `current_units` in commit f9a888ef

File: GeosUtil/unitconv_mod.F90 (hunk 7 above)
Comment (yantosca) [reply GeosUtil/unitconv_mod.F90]: @lizziel: This has now been updated in commit a8e07311.

File: GeosCore/aerosol_mod.F90 [hunk 15]
```diff
@@ -133,6 +133,10 @@ SUBROUTINE AEROSOL_CONC( Input_Opt,  State_Chm, State_Diag, &
     USE State_Met_Mod,     ONLY : MetState
     USE UnitConv_Mod
     USE TIME_MOD,          ONLY : GET_MONTH
+    USE Timers_Mod,        ONLY : Timer_End, Timer_Start
+#ifdef TOMAS
```
Comment (msulprizio) [inline GeosCore/aerosol_mod.F90:137]: These lines should be removed. I'm guessing they were added back in during a merge?

File: GeosCore/calc_met_mod.F90 [hunk 16]
```diff
@@ -218,9 +218,10 @@ SUBROUTINE AIRQNT( Input_Opt, State_Chm, State_Grid, State_Met, &
 ! !LOCAL VARIABLES:
 !
     ! Scalars
+    LOGICAL             :: t1,        t2
```
Comment (msulprizio) [inline GeosCore/calc_met_mod.F90:221]: Are these variables used anywhere? Can they be removed?

File: Interfaces/GCClassic/main.F90 (hunk 5 above)
Comment (yantosca) [reply Interfaces/GCClassic/main.F90:1894]: Nice catch @lizziel!  I've implemented this in commit 48860276.

**Review by msulprizio — CHANGES_REQUESTED** [review]

File: GeosCore/diagnostics_mod.F90 [hunk 17]
```diff
@@ -876,8 +885,13 @@ SUBROUTINE Set_SpcConc_Diags_MND  ( Input_Opt,  State_Chm, State_Diag,     &
...
     ! Verify that incoming State_Chm%Species units are kg/kg dry air.
-    IF ( State_Chm%Spc_Units /= KG_SPECIES_PER_KG_DRY_AIR ) THEN
-       ErrMsg = 'Incorrect species units in Set_SpcConc_Diags_MND!'
+    CALL Check_Units(                                                        &
+         State_Chm = State_Chm,                                              &
+         mapping   = State_Chm%Map_All,                                      &
+         units     = KG_SPECIES_PER_KG_DRY_AIR,                              &
+         RC        = RC                                                     )
+    IF ( RC /= GC_SUCCESS ) THEN
+       ErrMsg = 'Incorrect species units in Set_SpcConc_Diags_VVDry!'
```
[the remark this answers is not in the document]
Comment (yantosca) [reply GeosCore/diagnostics_mod.F90]: @lizziel: I've changed all of the unit conversion error messages in commit a80f173

File: GeosCore/diagnostics_mod.F90 [hunk 18]
```diff
@@ -466,9 +466,13 @@ SUBROUTINE Set_SpcAdj_Diagnostic( Input_Opt, State_Chm, State_Diag,    &
...
-    IF ( State_Chm%Spc_Units /= KG_SPECIES_PER_KG_DRY_AIR ) THEN
-       ErrMsg = 'Incorrect species units in Set_SpcAdj_Diags_VVDry!'    // &
-                 trim( UNIT_STR(State_Chm%Spc_Units) )
+    CALL Check_Units(                                                        &
+         State_Chm = State_Chm,                                              &
+         mapping   = State_Chm%Map_All,                                      &
+         units     = KG_SPECIES_PER_KG_DRY_AIR,                              &
+         RC        = RC                                                     )
+    IF ( RC /= GC_SUCCESS ) THEN
+       ErrMsg = 'Incorrect species units in Set_SpcConc_Diags_VVDry!'
```
[the remark this answers is not in the document]
Comment (yantosca) [reply GeosCore/diagnostics_mod.F90]: @lizziel: I've changed all of the unit conversion error messages in commit https://github.com/geoschem/geos-chem/commit/a80f173bb9d3eec9bdd3d57f9f213100a42600c5

File: GeosCore/chemistry_mod.F90 [hunk 19]
```diff
@@ -455,17 +459,10 @@ SUBROUTINE Do_Chemistry( Input_Opt,  State_Chm, State_Diag,                &
...
-                CALL GC_Error( ErrMsg, RC, ThisLoc )
-             ENDIF
-
-             ! Trap potential errors
-             IF ( RC /= GC_SUCCESS ) THEN
-                ErrMsg = 'Error encountered in ""!'
-                CALL GC_Error( ErrMsg, RC, ThisLoc )
-                RETURN
-             ENDIF
+             !IF ( State_Chm%Spc_Units /= KG_SPECIES ) THEN
```
[the remark this answers is not in the document]
Comment (yantosca) [reply GeosCore/chemistry_mod.F90]: @lizziel: Unit checks are now restored in ee72c2f3.

File: GeosCore/chemistry_mod.F90 [hunk 20]
```diff
@@ -548,11 +545,11 @@ SUBROUTINE Do_Chemistry( Input_Opt,  State_Chm, State_Diag,                &
                                FullRun    = .TRUE.,                          &
                                RC         = RC                              )
 
-             ! Check units (ewl, 10/5/15)
-             IF ( State_Chm%Spc_Units /= KG_SPECIES ) THEN
-                ErrMsg =  'Incorrect species units after CHEMSULFATE!'
-                CALL GC_Error( ErrMsg, RC, ThisLoc )
-             ENDIF
+             !! Check units (ewl, 10/5/15)
```
[the remark this answers is not in the document]
Comment (yantosca) [reply GeosCore/chemistry_mod.F90]: @lizziel: Unit checks are now restored in ee72c2f3.

**Comment by yantosca** [comment]
@msulprizio, @lizziel, @BettyCroft: I am running into issues with unit conversions for TOMAS, due to the fact that TOMAS calls unit conversions from either kg/kg dry to kg or kg/m2 to kg within the WASHOUT and AQOXID routines (see the `ConvertBox_*` routines in `GeosCore/unitconv_mod.F90.  Would anyone have any suggestions on how I could proceed?  How difficult would it be to convert TOMAS to accepting kg/kg dry air by default, so that we could eliminate the internal unit conversions?

**Comment by yantosca** [comment]
Thanks @BettyCroft.  I am kind of going down a rabbit hole and not making much progress.  If you could take a look at my unit conversion code that could be a start.

**Comment by BettyCroft** [comment]
Hi @yantosca, I can take look - might take me a little time to sort out exactly what is going on there. @lizziel helped to setup those unit conversions for TOMAS a few years ago and may have some insights based on that work.

**Comment by lizziel** [comment]
@yantosca, what is the main issue with the unit conversions for TOMAS? Is it possible to pass the list of species that need to be converted to convertBox, or is there a problem doing this?

**Comment by yantosca** [comment]
@lizziel @BettyCroft: the problem is that it is a little confusing because ConvertBox is used for in a couple of places:

1. Called from `WASHOUT` in `Do_Convection` (units are kg/kg dry), for wetdep species
2. Called from `WASHOUT` in the wetdep code (units are kg/m2), for wetdep species
3. Called from `AQOXID` in `tomas_mod.F90`, units are kg/m2, for some TOMAS species (I think).

I think I got kind of bogged down in the AQOXID calls, since those are made from a few places.  The problem that I was running into is that there are a lot of error checks for species units in tomas_mod.F90 that halt the run if all the species aren't in the same units.

**Comment by yantosca** [comment]
@lizziel, I can try that.  Stay tuned.

**Comment by BettyCroft** [comment]
@yantosca and @lizziel, thank you for this help with TOMAS.

**Comment by yantosca** [comment]
@lizziel, @msulprizio: I've run a 1-month Transport Tracer simulation (GCClassic) as a sanity check of mass conservation.  Here are the results:
```console
 Summary
 ------------------------------
 Max mass =   17.6563098477294 Tg
 Min mass =   17.6563095355969 Tg
 Abs diff =        312132.492 g
 Pct diff =      0.0000017678 %
```
The fuill file is here: [Passive_mass.PR_2072.txt](https://github.com/geoschem/geos-chem/files/14748302/Passive_mass.PR_2072.txt)

Is this what you would expect for good mass conservation?  To me, the % diff seems to be near the limit of numerical noise.

**Comment by yantosca** [comment]
@lizziel @msulprizio: I've run a sanity-check 1-month simulation with these unit conversion updates to test for mass conservation. The results are here:
```console
 Summary
 ------------------------------
 Max mass =   17.6563098477294 Tg
 Min mass =   17.6563095355969 Tg
 Abs diff =        312132.492 g
 Pct diff =      0.0000017678 %
```
The full file is here:  [Passive_mass.PR_2072.txt](https://github.com/geoschem/geos-chem/files/14748370/Passive_mass.PR_2072.txt)

It seems to me that the % diff is near to the limit of numerical noise (e.g. given that met fields are read in as REAL*4, which has about 6 digits of precision).  Let me know what you think.

Also: I forced the concentration of PassiveTracer in the initial restart file to be 1e-7 mol/mol dry everywhere.

**Comment by lizziel** [comment]
The mass difference is very low, but it is higher than what we see for our benchmarks. Here is the table for 14.2: https://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/14.2.0-rc.1/GCClassic/TransportTracers/BenchmarkResults/GCC_version_comparison/Tables/Passive_mass.txt

Would it be difficult to have a commit where all calls to convert units still convert all species? Then in subsequent commits change the components one by one to be reduced set. In theory the first commit should be zero diff to no-diff-to-bechmark. The other commits would introduce diffs, and we could more easily break it down per component.

**Comment by yantosca** [comment]
> Would it be difficult to have a commit where all calls to convert units still convert all species? Then in subsequent commits change the components one by one to be reduced set. In theory the first commit should be zero diff to no-diff-to-bechmark. The other commits would introduce diffs, and we could more easily break it down per component.

Thanks @lizziel.  I can try this.  We can comment out any defined mapping values, which will default to `State_Chm%Map_All`, or all species.  But this should now be zero-diff to 14.4.0-alpha.9, which I just merged up to.

**Comment by yantosca** [comment]
@lizziel: In commit bb76f8da, I commented out all of the mapping arrays.  I get the same results as before.  One line, however, has this difference:
```console
93c93
<  2019-01-22   17.6563096782163
---
>  2019-01-22   17.6563096782282
```
I am still investigating though.

**Comment by yantosca** [comment]
@lizziel: I did some mass conservation tests w/r/t 14.4.0-alpha.9 for a short time (1 week) as a sanity check.  Here is what I get:
```console
===============================================================================
Global mass of PassiveTracer

Ref = alpha.9
Dev = PR_2072
===============================================================================

 Date & Time                  Ref mass [Tg]             Dev mass [Tg]      Abs Diff    % Diff
 -----------------     --------------------      -------------------- -------------  --------
 2019-01-01 00:00          17.6563096646018          17.6563096646018    0.0000e+00     0.000
 2019-01-02 00:00          17.6563097334271          17.6563097334271    0.0000e+00     0.000
 2019-01-03 00:00          17.6563096472464          17.6563096472464    0.0000e+00     0.000
 2019-01-04 00:00          17.6563097381031          17.6563097381031    0.0000e+00     0.000
 2019-01-05 00:00          17.6563096420086          17.6563096420086    0.0000e+00     0.000
 2019-01-06 00:00          17.6563096769969          17.6563096769969    0.0000e+00     0.000
 2019-01-07 00:00          17.6563097517587          17.6563097517568   -1.9611e-12    -0.000
 2019-01-08 00:00          17.6563096589453          17.6563096589453    0.0000e+00     0.000
 
 Summary                                Ref                       Dev      Abs Diff    % Diff
 -----------------     --------------------      -------------------- -------------  --------
 Maximum mass [Tg]         17.6563097517587          17.6563097517568   -1.9611e-12    -0.000
 Minimum mass [Tg]         17.6563096420086          17.6563096420086    0.0000e+00     0.000
 Abs diff [g]          109750.1645119791647      109748.2034140284668   -1.9611e+00    -0.002
 % difference               0.0000006215918           0.0000006215806   -1.1107e-11    -0.002

 Start mass [Tg]           17.6563096646018          17.6563096646018    0.0000e+00     0.000
 End mass [Tg]             17.6563096589453          17.6563096589453    0.0000e+00     0.000
 Abs diff [g]           -5656.5063744073996       -5656.5063744073996    0.0000e+00    -0.000
 % difference              -0.0000000320367          -0.0000000320367    0.0000e+00    -0.000

 Mean mass [Tg]            17.6563096891360          17.6563096891357   -2.4514e-13    -0.000
 Variance [Tg]          1.7396969847601e-15       1.7396662828534e-15   -3.0702e-20    -0.002
```
There is some difference at the 13th digit, which is caused by wet deposition.  If I disable wetdep, these differences go away.  The PassiveTracer should not be affected by wetdep but maybe there is a small discrepancy in air mass or something.  Let me know what you think.

**Comment by yantosca** [comment]
@lizziel: Also note, I made sure that the passive species in the restart file was set to a constant value.  I used this script to edit the PassiveTracer starting concentration:
```python
#!/usr/bin/env python3

import numpy as np
import xarray as xr

ifile="./GEOSChem.Restart.20190101_0000z.nc4"
ofile="./new.GEOSChem.Restart.20190101_0000z.nc4"

with xr.set_options(keep_attrs=True):

    data = xr.open_dataset(ifile)

    arr = data["SpeciesRst_PassiveTracer"].values
    arr[:,:,:,:] = 1.0e-7

    data["SpeciesRst_PassiveTracer"].values = arr

    data.to_netcdf(ofile)
```

**Comment by yantosca** [comment]
@lizziel: If I shut off wetdep, I get this output:
```console
===============================================================================
Global mass of PassiveTracer

Ref = alpha.9
Dev = PR_2072
===============================================================================

 Date & Time                  Ref mass [Tg]             Dev mass [Tg]      Abs Diff    % Diff
 -----------------     --------------------      -------------------- -------------  --------
 2019-01-01 00:00          17.6563096646018          17.6563096646018    0.0000e+00     0.000
 2019-01-02 00:00          17.6563097334271          17.6563097334271    0.0000e+00     0.000
 2019-01-03 00:00          17.6563096472464          17.6563096472464    0.0000e+00     0.000
 2019-01-04 00:00          17.6563097381031          17.6563097381031    0.0000e+00     0.000
 2019-01-05 00:00          17.6563096420086          17.6563096420086    0.0000e+00     0.000
 2019-01-06 00:00          17.6563096769969          17.6563096769969    0.0000e+00     0.000
 2019-01-07 00:00          17.6563097517568          17.6563097517568    0.0000e+00     0.000
 2019-01-08 00:00          17.6563096589453          17.6563096589453    0.0000e+00     0.000
 
 Summary                                Ref                       Dev      Abs Diff    % Diff
 -----------------     --------------------      -------------------- -------------  --------
 Maximum mass [Tg]         17.6563097517568          17.6563097517568    0.0000e+00     0.000
 Minimum mass [Tg]         17.6563096420086          17.6563096420086    0.0000e+00     0.000
 Abs diff [g]          109748.2034140284668      109748.2034140284668    0.0000e+00     0.000
 % difference               0.0000006215806           0.0000006215806    0.0000e+00     0.000

 Start mass [Tg]           17.6563096646018          17.6563096646018    0.0000e+00     0.000
 End mass [Tg]             17.6563096589453          17.6563096589453    0.0000e+00     0.000
 Abs diff [g]           -5656.5063744073996       -5656.5063744073996    0.0000e+00    -0.000
 % difference              -0.0000000320367          -0.0000000320367    0.0000e+00    -0.000

 Mean mass [Tg]            17.6563096891357          17.6563096891357    0.0000e+00     0.000
 Variance [Tg]          1.7396662828534e-15       1.7396662828534e-15    0.0000e+00     0.000
```

**Comment by yantosca** [comment]
@lizziel: I was able to get this output from the `compare_diags.py` script:
```console
... Creating single-level plots
... Creating zonal mean plots
... Printing totals and differences
... Only showing variables with |absolute difference| > 0.0
Variable               Ref=alpha.9              Dev=PR #2072             Dev - Ref
SpeciesRst_PassiveTracer : 0.02384641             | 0.02384641             | -7.105427357601002e-15 
```
But this may just be numerical noise at the limit of representation.

**Comment by lizziel** [comment]
With respect to no diff, looks good to me!

**Comment by yantosca** [comment]
@lizziel @msulprizio: Thanks!  I am doing integration test off of alpha.9 (where the branch is now).  Then will merge up to dev/14.4.0 (locally) and test after the volcano update.

**Comment by yantosca** [comment]
I've merged 14.4.0-alpha.12 into the `feature/unitconv-per-species-category` branch and re-ran integration tests.  The GEOS-Chem Classic tests all passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #965e66d GEOS-Chem submodule update: Add hotfix to correct typo in volcano emission file name
GEOS-Chem #49782e849 Make sure REEVAPSO2 is properly defined in kg
HEMCO     #fddcae5 Update version to 3.8.1 for release

Using 24 OpenMP threads
Number of execution tests: 29

Submitted as SLURM job: 28408502
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
@msulprizio, @lizziel: I ran a set of integration tests w/o the carbon simulation tests.  All integration tests passed.   We will look into the carbon simulation issues in a separate PR. I think it is OK to merge so as not to hold up the 14.4.0 release.
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #85f9efc GEOS-Chem submodule update: Add hotfix to correct typo in volcano emission file name
GEOS-Chem #49782e849 Make sure REEVAPSO2 is properly defined in kg
HEMCO     #fddcae5 Update version to 3.8.1 for release

Number of execution tests: 6

Submitted as SLURM job: 29233300
==============================================================================
 
Execution tests:
------------------------------------------------------------------------------
gchp_merra2_fullchem................................Execute Simulation....PASS
gchp_merra2_fullchem_benchmark......................Execute Simulation....PASS
gchp_merra2_fullchem_RRTMG..........................Execute Simulation....PASS
gchp_merra2_fullchem_TOMAS15........................Execute Simulation....PASS
gchp_merra2_tagO3...................................Execute Simulation....PASS
gchp_merra2_TransportTracers........................Execute Simulation....PASS
 
Summary of test results:
------------------------------------------------------------------------------
Execution tests passed: 6
Execution tests failed: 0
Execution tests not yet completed: 0

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

**Comment by yantosca** [comment]
Am merging locally up to 14.4.0 and re-running integration tests.

**Comment by gopikrishnangs44** [comment]
Hi @yantosca 

I am trying to simulate GCAP. 

Encountered the same error, as below

```
HEMCO: Opening ./Restarts/GEOSChem.Restart.20450101_0000z.nc4

HEMCO ERROR: Cannot find field SPC_BUTDI. Please check variable name in the config. file

HEMCO ERROR: Error encountered in routine HCOIO_Read!

HEMCO ERROR: Error in HCOIO_DATAREAD called from HEMCO ReadList_Fill: SPC_BUTDI
 --> LOCATION: ReadList_Fill (HCO_ReadList_Mod.F90)

HEMCO ERROR: Error in called ReadList_Fill (7) from HEMCO ReadList_Read
 --> LOCATION: ReadList_Read (HCO_ReadList_Mod.F90)
 Error in ReadList_Read called from hco_run
===============================================================================
GEOS-Chem ERROR: Error encountered in "HCO_Run"!
 -> at HCOI_GC_Run (in module GeosCore/hco_interface_gc_mod.F90)

THIS ERROR ORIGINATED IN HEMCO!  Please check the HEMCO log file for
additional error messages!
===============================================================================


Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x15555363eb4f in ???
#1  0x155554a63169 in sflush
        at /local/gg2995/spack-stage/spack-stage-gcc-10.2.0-ca5qgfppgl4tppua3svba6vehsuvjayp/spack-src/libgfortran/io/unix.h:89
#2  0x456c62 in __emissions_mod_MOD_emissions_run
        at /burg/fiore_new/users/gg2995/test2/gc_2x25_ModelE2.1_fullchem/CodeDir/src/GEOS-Chem/GeosCore/emissions_mod.F90:184
#3  0x4068c4 in geos_chem
        at /burg/fiore_new/users/gg2995/test2/gc_2x25_ModelE2.1_fullchem/CodeDir/src/GEOS-Chem/Interfaces/GCClassic/main.F90:667
#4  0x405556 in main
        at /burg/fiore_new/users/gg2995/test2/gc_2x25_ModelE2.1_fullchem/CodeDir/src/GEOS-Chem/Interfaces/GCClassic/main.F90:32
```

**Comment by lizziel** [comment]
@gopikrishnangs44, please create a new issue to request help.

**Comment by gopikrishnangs44** [comment]
HI @lizziel

I figured it out by changing the SPC restart from EY to CYS.

Thank for the response.
