### PR TITLE
[PULL REQUEST] Bug fix: Remove second underscore from state_chm Hg fields (closes #957)

### LINKED ISSUE #957: [BUG/ISSUE] Restart files in Hg simulation
Dear all,

I would like to make a question. I am using geos chem 13.0.2 for mercury simulation on 2x2.5 grid.

my mercury menu in input.geos is the following:
```
%%% MERCURY MENU %%% :
Error check tag/tot Hg? : F
Use dynamic ocean Hg? : F
Preindustrial sim? : F
Use GTMM soil model? : F
GTMM Hg rst file (bpch) : GTM.totHg.YYYYMMDDhh
Use Arctic river Hg? : T
Tie HgII(aq) red to UVB?: T.
```
The error reported is about the restart files and related with the snowpack hg source.
```
Restart.filename: './GEOSChem.Restart.%y4%m2%d2_%h2%n2z.nc4',
Restart.format: 'CFIO',
Restart.frequency: 00000100 000000
Restart.duration: 00000100 000000
Restart.mode: 'time-averaged'
Restart.fields: 'SpeciesRst_?ALL? ', 'GIGCchem',
'Met_DELPDRY ', 'GIGCchem',
'Met_PS1WET ', 'GIGCchem',
'Met_PS1DRY ', 'GIGCchem',
'Met_SPHU1 ', 'GIGCchem',
'Met_TMPU1 ', 'GIGCchem',
# 'Chem_OceanHg0 ', 'GIGCchem',
# 'Chem_OceanHg2 ', 'GIGCchem',
# 'Chem_OceanHgP ', 'GIGCchem',
# 'Chem_SnowHgOcean ', 'GIGCchem',
# 'Chem_SnowHgLand ', 'GIGCchem',
# 'Chem_SnowHgOceanStored ', 'GIGCchem',
# 'Chem_SnowHgLandStored ', 'GIGCchem',
```
When the restart fields are including ONLY the SpeciesRst_Hg0-Hg2-HgP and the MET fields, the simulation is running.

When I add the 'Chem_OceanHg0 ', 'Chem_OceanHg2 ','Chem_OceanHgP ', 'GIGCchem' 'Chem_SnowHgOcean ', 'Chem_SnowHgLand ',
'Chem_SnowHgOceanStored ', 'Chem_SnowHgLandStored ', I am getting the following error for each one of the snow/ocean variables:
```
HISTORY (INIT): Opening ./HISTORY.rc
===============================================================================
GEOS-Chem ERROR: CHEM_OCEANHG0 is not found in the registry for the CHEM object!
-> at Registry_Lookup (in Headers/registry_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Could not locate Chem_OceanHg0 chemistry state registry.
-> History_AddItemToCollection (in History/history_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Could not add diagnostic "Chem_OceanHg0" to collection: Restart
-> at History_ReadCollectionData (in module History/history_mod.F90)

-> ERROR occurred at (or near) line 70 of the HISTORY.rc file
===============================================================================
```
Is it a variable name bug, the way things are computed changed or I am doing something wrong??Is it sure that this, is not affecting the other mechanisms and the results?

Looking forward to your reply,

Thank you very much!

### PR DESCRIPTION
**Pull request by yantosca**
This is the corresponding PR to #957.  It fixes an issue in the registering of several Hg-related fields in `state_chem_mod.F90`.

### CODE REVIEW

**Review by laestrada — APPROVED** [review]
This looks like a straightforward fix. Approved

File: Headers/state_chm_mod.F90 [hunk 1]
```diff
@@ -2395,21 +2395,25 @@ SUBROUTINE Init_Hg_Simulation_Fields( Input_Opt, State_Chm, State_Grid,    &
...
     ALLOCATE( State_Chm%Hg0_Id_List( State_Chm%N_Hg_CATS ), STAT=RC )
+    CALL GC_CheckVar( 'State_Chm%Hg0_Id_List', 0, RC )
     IF ( RC /= GC_SUCCESS ) RETURN
     State_Chm%Hg0_Id_List = 0
 
     ! Index array: Hg2 species # <--> Hg0 category #
     ALLOCATE( State_Chm%Hg2_Id_List( State_Chm%N_Hg_CATS ), STAT=RC )
+    CALL GC_CheckVar( 'State_Chm%Hg2_Id_List', 0, RC )
     IF ( RC /= GC_SUCCESS ) RETURN
     State_Chm%Hg2_Id_List = 0
```
Comment (laestrada) [inline Headers/state_chm_mod.F90:2406]: @yantosca if I am understanding the behavior correctly, adding in GC_Checkvar will throw an error if the variable isn't successfully allocated. So would the following if statement ever get tripped? Since failure mode would now halt execution?

Comment (yantosca) [reply Headers/state_chm_mod.F90:2406]: So `GC_CheckVar` just defines an error message depending on whether or not the error happened at allocation, registration, or deallocation.  Then it calls `GC_Error`, which prints the error message as well as forcing `RC = GC_FAILURE`.  Then RC comes back from `GC_CheckVar` as failure, which will keep returning the program control to the top level where it'll stop gracefully.

```F90
!EOC
!------------------------------------------------------------------------------
!                  GEOS-Chem Global Chemical Transport Model                  !
!------------------------------------------------------------------------------
!BOP
!
! !IROUTINE: GC_CheckVar
!
! !DESCRIPTION: Wrapper routine for GC\_Error.  Prints an error message
!  if there is an allocation or registration error.  This is intended to
!  be called from the state initialization method (e.g. Init\_State\_Met).
!\\
!\\
! !INTERFACE:
!
  SUBROUTINE GC_CheckVar( Variable, Operation, RC )
!
! !INPUT PARAMETERS:
!
    CHARACTER(LEN=*), INTENT(IN)    :: Variable   ! Name of variable to check
    INTEGER,          INTENT(IN)    :: Operation  ! 0=Allocate
                                                  ! 1=Register
                                                  ! 2=Deallocate
!
! !OUTPUT PARAMETERS:
!
    INTEGER,          INTENT(INOUT) :: RC         ! Success or failure
!
! !REMARKS:
!  You also need to add an
!    IF ( RC /= GC_SUCCESS ) RETURN
!  from the calling routine for proper error handling.
!
! !REVISION HISTORY:
!  27 Jun 2017 - R. Yantosca - Initial version
!  See https://github.com/geoschem/geos-chem for complete history
!EOP
!------------------------------------------------------------------------------
!BOC
!
! !LOCAL VARIABLES:
!
  ! Strings
  CHARACTER(LEN=255) :: ErrMsg, ThisLoc

  !=========================================================================
  ! Initialize
  !=========================================================================

  ! Define error message
  SELECT CASE( Operation )
     CASE( 1 )
        ErrMsg = 'Could not register '   // TRIM( Variable ) // '!'
     CASE( 2 )
        ErrMsg = 'Could not deallocate ' // TRIM( Variable ) // '!'
     CASE DEFAULT
        ErrMsg = 'Could not allocate '   // TRIM( Variable ) // '!'
  END SELECT

  ! Define location string
  ThisLoc   = ' -> at GC_CheckVar (in Headers/errcode_mod.F90)'

  !=========================================================================
  ! Display error message if necessary
  !=========================================================================
  IF ( RC /= GC_SUCCESS ) THEN
     CALL GC_Error( ErrMsg, RC, ThisLoc )
  ENDIF

  END SUBROUTINE GC_CheckVar
```

Comment (laestrada) [reply Headers/state_chm_mod.F90:2406]: Got it, thanks!
