### PR TITLE
UCX bug fixes : (1) Use proper 4th index for WERADIUS array; (2) Get density of black carbon from the species database

### LINKED ISSUE #2169: Black carbon radius and density in gravitational settling of stratospheric aerosols
### Name and Institution (Required)

Name: Connor Barker
Institution: University College London

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

To the GC team,

I am working on adding a new aerosol species into GEOS-Chem v14.3.0, which undergoes gravitational settling in the stratosphere, and I have some queries regarding the current code. This process is handled in the settle_strat_aer subroutine in GeosCore/ucx_mod.F90, which adds gravitational settling of sulfate and hydrophilic black carbon. 

image

Firstly, the code at line 927 loads the wet radius of BCPI from the WERADIUS array, which points to State_Chm%WetAeroRadi. However the index should be WERADIUS(I,J,L,2 **+NDUST** ), not WERADIUS(I,J,L,2) to account for the dust radii which occupy WERADIUS(:,:,:,1-7). Currently the code assigns the wet radius of BCPI as the dry radius of MDUST2, which I have confirmed by printing the 

Secondly, the value for RHO(IBC) on line 938 is commented to say it is taken from aerosol_mod for MSDENS(2), which loads the density from species_database.yml. However BCDEN is instead defined as “1000.e+0_fp ! density (kg/m3)” in ucx_mod.F90 at line 813, and defined differently in the species_database.yml value as 1800 kg/m3. Should the density of BCPI be instead loaded in from species_database.yml, or was the choice of 1000 kg/m3 deliberate?

Thanks,
Connor

image

### PR DESCRIPTION
**Pull request by yantosca**
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/CONTRIBUTING.html)

### Describe the update

This is the companion PR to issue #2162, raised by @cbarker211.  It does the following:

1. Now use `WERADIUS(I,J,L,2+NDUST)` instead of `WERADIUS(I,J,L,2)`.
2. Now gets the density of black carbon from the species database instead of setting it to 1000 kg/m3.

Integration tests are running.

### Expected changes

Please provide details on how this update will impact model output and include plots or tables as needed.

### Reference(s)

N/A

### Related Github Issue(s)
- Closes #2169

### CODE REVIEW

File: GeosCore/ucx_mod.F90 [hunk 1]
```diff
@@ -924,7 +921,9 @@ SUBROUTINE SETTLE_STRAT_AER( Input_Opt, State_Chm, State_Grid, State_Met, RC )
           IF (RUNCALC) THEN
              ! Need to translate for BC radii
              IF ( State_Met%InChemGrid(I,J,L) ) THEN
-                RWET(IBC) = WERADIUS(I,J,L,2)*1.e-2_fp
+                ! NOTE: Replace 2 with 2+NDUST
+                ! See: https://github.com/geoschem/geos-chem/issues/2169
```
Comment (msulprizio) [inline GeosCore/ucx_mod.F90:925]: I would suggest removing these lines. People can always use Git blame to view the line history.

File: GeosCore/ucx_mod.F90 [hunk 2]
```diff
@@ -934,8 +933,9 @@ SUBROUTINE SETTLE_STRAT_AER( Input_Opt, State_Chm, State_Grid, State_Met, RC )
 #endif
              ENDIF
 
-             ! Taken from aerosol_mod (MSDENS(2))
-             RHO(IBC) = BCDEN
+             ! Now use the density of BCPI from the species database.
+             ! See: https://github.com/geoschem/geos-chem/issues/2169
```
Comment (msulprizio) [inline GeosCore/ucx_mod.F90:937]: I also suggest removing this line

**Review by msulprizio — APPROVED** [review]
Looks good. I just have two suggested changes but will approve now. I personally do not like using URLs in code and would recommend people use Git blame if looking for the history of a line.

File: GeosCore/ucx_mod.F90 (hunk 2 above)
Comment (yantosca) [reply GeosCore/ucx_mod.F90]: Now removed in commit fda4d7b.

File: GeosCore/ucx_mod.F90 (hunk 1 above)
Comment (yantosca) [reply GeosCore/ucx_mod.F90]: Now removed in commit https://github.com/geoschem/geos-chem/commit/fda4d7bbfe7c16da33ad6422b9b117ee160f1a5a.

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #898c882 GEOS-Chem submod update: Merge PR #2166 (Remove bpch diags )
GEOS-Chem #4c8e2afc6 Now reference NDUST from CMN_SIZE_Mod in settle_strat_aer
HEMCO     #f807e1a Update HEMCO version number to 3.8.0 in preparation for release

Using 24 OpenMP threads
Number of execution tests: 26

Submitted as SLURM job: 22547219
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 ```

**Comment by yantosca** [comment]
All GCHP integration tests passed:
```console
==============================================================================
GCHP: Execution Test Results

GCHP      #04bde0c GEOS-Chem submod update: Merge PR #2166 (Remove bpch diags )
GEOS-Chem #4c8e2afc6 Now reference NDUST from CMN_SIZE_Mod in settle_strat_aer
HEMCO     #f807e1a Update HEMCO version number to 3.8.0 in preparation for release

Number of execution tests: 6

Submitted as SLURM job: 22567065
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
