### PR TITLE
Turn off the MEGAN extension for fullchem "non-benchmark" simulations

### LINKED ISSUE #2319: MEGAN extension is turned on by default in GCHP run directory
### Your name

Bob Yantosca

### Your affiliation

Harvard + GCST

### What happened? What did you expect to happen?

The HEMCO MEGAN extension is turned on by default when creating a GCHP run directory.  Found by @yuanjianz.

Offline biogenic emissions are recommended for standard full-chemistry GCHP simulations. Having both offline biogenic VOC and MEGAN turned on may double count some emissions.

### What are the steps to reproduce the bug?

Created a GCHP run directory and look at the HEMCO_Config.rc

### Please attach any relevant configuration and log files.

_No response_

### What GEOS-Chem version were you using?

14.4.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc10

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCHP

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

14.4.0

### What meterology fields did you use?

MERRA-2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by yantosca**
### Name and Institution (Required)
Name: Bob Yantosca
Institution: Harvard + GCST

### Describe the update
This is the companion PR to #2319.  We have updated the run directory creation scripts and HEMCO_Config.rc template files so that the MEGAN emissions are enabled for the full-chemistry "benchmark" simulation and disabled for all other full-chemistry simulations. 

### Expected changes
This should be a zero-diff update

### Related Github Issue
- Closes #2319

### CODE REVIEW

**Comment by yantosca** [comment]
I created run directories for the GEOS-Chem Classic aerosol-only and fullchem simulations.  The MEGAN emissions are only turned on in the benchmark simulation.
```console
$ g "108     MEGAN" */HEMCO_Config.rc
aer_only/HEMCO_Config.rc:174:           108     MEGAN                  : off   ISOP/ACET/PRPE/C2H4/ALD2/MOH/EOH/MTPA/MTPO/LIMO/SESQ/SOAP/SOAS
fullchem_apm/HEMCO_Config.rc:197:       108     MEGAN                  : off    ISOP/ACET/PRPE/C2H4/ALD2/MOH/EOH/MTPA/MTPO/LIMO/SESQ/SOAP/SOAS
fullchem_benchmark/HEMCO_Config.rc:197: 108     MEGAN                  : on     ISOP/ACET/PRPE/C2H4/ALD2/MOH/EOH/MTPA/MTPO/LIMO/SESQ/SOAP/SOAS
fullchem_csoa/HEMCO_Config.rc:197:      108     MEGAN                  : off    ISOP/ACET/PRPE/C2H4/ALD2/MOH/EOH/MTPA/MTPO/LIMO/SESQ/SOAP/SOAS
fullchem_csoasvpoa/HEMCO_Config.rc:197: 108     MEGAN                  : off    ISOP/ACET/PRPE/C2H4/ALD2/MOH/EOH/MTPA/MTPO/LIMO/SESQ/SOAP/SOAS
fullchem_mpoa/HEMCO_Config.rc:197:      108     MEGAN                  : off    ISOP/ACET/PRPE/C2H4/ALD2/MOH/EOH/MTPA/MTPO/LIMO/SESQ/SOAP/SOAS
fullchem_rrtmg/HEMCO_Config.rc:197:     108     MEGAN                  : off    ISOP/ACET/PRPE/C2H4/ALD2/MOH/EOH/MTPA/MTPO/LIMO/SESQ/SOAP/SOAS
fullchem_std/HEMCO_Config.rc:197:       108     MEGAN                  : off    ISOP/ACET/PRPE/C2H4/ALD2/MOH/EOH/MTPA/MTPO/LIMO/SESQ/SOAP/SOAS
fullchem_tomas/HEMCO_Config.rc:197:     108     MEGAN                  : off    ISOP/ACET/PRPE/C2H4/ALD2/MOH/EOH/MTPA/MTPO/LIMO/SESQ/SOAP/SOAS
```

**Comment by yantosca** [comment]
This also works for GCHP:
```console
gchp_fullchem_bmk/HEMCO_Config.rc:196:108     MEGAN                  : on     ISOP/ACET/PRPE/C2H4/ALD2/MOH/EOH/MTPA/MTPO/LIMO/SESQ/SOAP/SOAS
gchp_fullchem_std/HEMCO_Config.rc:196:108     MEGAN                  : off    ISOP/ACET/PRPE/C2H4/ALD2/MOH/EOH/MTPA/MTPO/LIMO/SESQ/SOAP/SOAS
```

**Comment by yantosca** [comment]
All GEOS-Chem Classic integration tests passed:
```console
==============================================================================
GEOS-Chem Classic: Execution Test Results

GCClassic #30aeed4 GEOS-Chem submod update: Merge PR #2369 (Fixes for satellite diags)
GEOS-Chem #5971dcb0c Turn off MEGAN extension for standard fullchem simulations
HEMCO     #2192e0e HEMCO 3.9.1 release

Using 24 OpenMP threads
Number of execution tests: 28

Submitted as SLURM job: 39495288
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
However, this is not a zero-diff update.  We will have to merge into dev/14.5.0.

**Comment by yantosca** [comment]
All GCHP integration tests passed
```
==============================================================================
GCHP: Execution Test Results

GCHP      #95a745c GEOS-Chem submod update: Merge PR #2369 (Fixes for satellite diags)
GEOS-Chem #5971dcb0c Turn off MEGAN extension for standard fullchem simulations
HEMCO     #

Number of execution tests: 11

Submitted as SLURM job: 39495563
==============================================================================

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  All execution tests passed!  %%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
All tests were zero-diff to PR #2369 except for:
- fullchem
- fullchem_RRTMG
- fullchem_TOMAS15

Due to similar reasons as listed in the previous comment.

File: run/GCClassic/createRunDir.sh [hunk 1]
```diff
@@ -976,6 +981,7 @@ else
 	RUNDIR_VARS+="RUNDIR_DUSTDEAD_EXT='on '\n"
 	RUNDIR_VARS+="RUNDIR_SEASALT_EXT='on '\n"
 	RUNDIR_VARS+="RUNDIR_SOILNOX_EXT='on '\n"
+	RUNDIR_VARS+="RUNDIR_MEGAN_EXT='on '\n"
```
Comment (lizziel) [inline run/GCClassic/createRunDir.sh:984]: It looks like RUNDIR_MEGAN_EXT is never set if using GCAP. Is that oversight?

Comment (yantosca) [reply run/GCClassic/createRunDir.sh]: @lizziel: Yes it was.  Now fixed in 207c9c6.

**Review by lizziel — APPROVED** [review]
Looks good to merge.
